---
- name: setup smokeping
  block:
    - name: install smokeping related packages
      apt:
        name: "{{ packages }}"
        state: "latest"
        update_cache: yes
        cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
      vars:
        packages:
          - smokeping
          - fcgiwrap
          - nginx
    - name: setup smokeping nginx config
      copy:
        src: "smokeping_nginx"
        dest: "/etc/nginx/sites-available/smokeping"
        owner: "root"
        group: "root"
        mode: "0644"
    - name: activate smokeping nginx config
      file:
        src: /etc/nginx/sites-available/smokeping
        dest: /etc/nginx/sites-enabled/smokeping
        owner: root
        group: root
        state: link
    - name: delete default nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: install smokeping configuration
      template:
        src: "{{ item }}.j2"
        dest: "/etc/smokeping/config.d/{{ item }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - Targets
    - name: start service
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - smokeping.service
        - fcgiwrap.service
        - nginx.service
  tags:
    - smokeping
